# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name            = "uefi-hello-world"
version         = "0.1.0"
edition         = "2018"
publish         = false

[dependencies]
wchar           = "0.10"
